### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by donmullen** [dmotz/natal#23]
Got the following popup when running:

natal init FutureApp --interface om-next

/Users/don/src/react-native/future-app/native/node_modules/react-native/packager/packager.js:15
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Process terminated. Press <enter> to close the window
# 

Resulting in this in the terminal:

$ natal init FutureApp --interface om-next
Creating FutureApp

Creating Leiningen project
Updating Leiningen project
Compiling ClojureScript
Creating React Native skeleton
Installing Pod dependencies
Updating Xcode project
Creating Natal config
Compiling Xcode project
Command failed: xcodebuild -workspace native/ios/FutureApp.xcworkspace -scheme FutureApp -destination platform='iOS Simulator',OS=latest,id='C805F622-C03C-47C1-8AF1-BF08FC33760A' test

**Comment by dmotz** [comment]
What version of Node do you have installed?

**Comment by mfikes** [comment]
@donmullen you managed to sort this one out, rught? Maybe upgraded node?

**Comment by dmotz** [comment]
Are you using nvm? If so try upgrading nvm's version as well, as explained here: https://github.com/facebook/react-native/issues/3243#issuecomment-155677275
