### ISSUE TITLE
Add some examples to README or Wiki

### ISSUE THREAD

**Issue by felipebueno** [dmotz/natal#29]
Hi.

I've been experimenting natal for the last three days and I must say it's a great project. Today I started developing my first serious app with it.

I have some experience developing with Clojure and Java but now I need to learn React Native and ClojureScript for a project we started a couple weeks ago.

Is there a sample app using natal? Or any examples to help me learning how to "compose my components" properly?

Thanks in advance,

Felipe

**Comment by felipebueno** [comment]
For example: I'm trying to write this snippet from the [docs](http://facebook.github.io/react-native/docs/alertios.html#content) in cljs but it throws an error.

##### JSX
```JSX
AlertIOS.alert(
    'Foo Title',
    'My Alert Msg',
    [
        {text: 'Foo', onPress: () => console.log('Foo Pressed!')},
        {text: 'Bar', onPress: () => console.log('Bar Pressed!')},
    ]
)
```
##### ClojureScript (om-next)
```Clojure
(alert
  "Foo Title"
  "My Alert Msg"
  [{:text "Foo" :onPress #()}
   {:text "Bar" onPress: #()}])
```

```
clojure.lang.ExceptionInfo: Invalid token: onPress: {:type :reader-exception, :line 1, :column 84, :file "NO_SOURCE_FILE"}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at clojure.tools.reader.reader_types$reader_error.doInvoke(reader_types.clj:331)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at clojure.tools.reader$read_symbol.invoke(reader.clj:329)
	at clojure.tools.reader$read_STAR_$fn__1852.invoke(reader.clj:893)
	at clojure.tools.reader.reader_types$log_source_STAR_$fn__1543.invoke(reader_types.clj:241)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.reader.reader_types$log_source_STAR_.invoke(reader_types.clj:240)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:878)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:195)
	at clojure.tools.reader$read_map.invoke(reader.clj:242)
	at clojure.tools.reader$read_STAR_$fn__1852.invoke(reader.clj:889)
	at clojure.tools.reader.reader_types$log_source_STAR_$fn__1543.invoke(reader_types.clj:241)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.reader.reader_types$log_source_STAR_.invoke(reader_types.clj:240)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:878)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:195)
	at clojure.tools.reader$read_vector.invoke(reader.clj:226)
	at clojure.tools.reader$read_STAR_$fn__1852.invoke(reader.clj:889)
	at clojure.tools.reader.reader_types$log_source_STAR_$fn__1543.invoke(reader_types.clj:241)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.reader.reader_types$log_source_STAR_.invoke(reader_types.clj:240)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:878)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:195)
	at clojure.tools.reader$read_list.invoke(reader.clj:208)
	at clojure.tools.reader$read_STAR_$fn__1852.invoke(reader.clj:889)
	at clojure.tools.reader.reader_types$log_source_STAR_$fn__1543.invoke(reader_types.clj:241)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.reader.reader_types$log_source_STAR_.invoke(reader_types.clj:240)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:878)
	at clojure.tools.reader$read.invoke(reader.clj:938)
	at cljs.repl$repl_read.invoke(repl.cljc:96)
	at cljs.repl$repl_read.invoke(repl.cljc:89)
	at cljs.repl$repl_STAR_$read_eval_print__5642$fn__5643.invoke(repl.cljc:848)
	at cljs.repl$repl_STAR_$read_eval_print__5642.invoke(repl.cljc:841)
	at cljs.repl$repl_STAR_$fn__5648$fn__5657.invoke(repl.cljc:895)
	at cljs.repl$repl_STAR_$fn__5648.invoke(repl.cljc:894)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1146)
	at cljs.repl$repl_STAR_.invoke(repl.cljc:858)
	at cemerick.piggieback$run_cljs_repl.invoke(piggieback.clj:169)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:634)
	at cemerick.piggieback$evaluate.invoke(piggieback.clj:258)
	at clojure.lang.Var.invoke(Var.java:379)
	at cemerick.piggieback$wrap_cljs_repl$fn__6132$fn__6134$fn__6135.invoke(piggieback.clj:290)
	at cemerick.piggieback$enqueue$fn__6118.invoke(piggieback.clj:246)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__660.invoke(interruptible_eval.clj:159)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by felipebueno** [comment]
For example: I'm trying to write this snippet from [RN's docs](http://facebook.github.io/react-native/docs/alertios.html#content) in cljs but it throws an error.

##### JSX

``` JSX
AlertIOS.alert(
    'Foo Title',
    'My Alert Msg',
    [
        {text: 'Foo', onPress: () => console.log('Foo Pressed!')},
        {text: 'Bar', onPress: () => console.log('Bar Pressed!')},
    ]
)
```

##### ClojureScript (om-next)

``` Clojure
(alert
  "Foo Title"
  "My Alert Msg"
  [{:text "Foo" :onPress #()}
   {:text "Bar" :onPress #()}])
```

```
TypeError: buttons.forEach is not a function. (In 'buttons.forEach', 'buttons.forEach' is undefined)
```

**Comment by dmotz** [comment]
Natal is fairly new so there aren't a lot of example apps I know of yet, but here are two that should help:

https://github.com/iamjarvo/zooborns
https://github.com/dvcrn/om-react-native-demo

As for the issue you're seeing, I think you need to wrap the array argument in `clj->js` which will recursively convert the ClojureScript vector and maps into native Javascript objects.

Right now the Natal Shell interop macros are very naive and simply dump the arguments as given.

In the future we could try to make it more aware of argument types so it could auto convert them.

**Comment by dmotz** [comment]
You can also try writing your example using tagged literals like:

``` clojure
(alert
  "Foo Title"
  "My Alert Msg"
  #js [#js {:text "Foo" :onPress #()}
       #js {:text "Bar" :onPress #()}])
```

Or at runtime with `clj->js`:

``` clojure
(alert
  "Foo Title"
  "My Alert Msg"
  (clj->js 
    [{:text "Foo" :onPress #()}
     {:text "Bar" :onPress #()}]))

```

**Comment by felipebueno** [comment]
Great! Thank you for the quick reply, @dmotz :)

**Comment by chadhs** [comment]
@dmotz @felipebueno here's a quick markdown doc i made showing a getting started with emacs example, let me know if you want me to modify and drop in the wiki:

[Driving a Natal Project with the Emacs CIDER REPL](https://github.com/dmotz/natal/wiki/Driving-a-Natal-Project-with-the-Emacs-CIDER-REPL)

**Comment by dmotz** [comment]
I added links to example apps to the readme. Feel free to add others you know of.

@chadhs Hoping to make the Cider compatibility more painless, but in the meantime feel free to add your guide to the wiki.

**Comment by chadhs** [comment]
done: [Driving a Natal Project with the Emacs CIDER REPL](https://github.com/dmotz/natal/wiki/Driving-a-Natal-Project-with-the-Emacs-CIDER-REPL)
