### ISSUE TITLE
Error building DependencyGraph: TypeError: Cannot read property 'root' of null

### ISSUE THREAD

**Issue by kahunamoore** [dmotz/natal#33]
My setup:

natal: 0.1.11
OSX: El Capitan 10.11.1 (15B42)
nodejs: v4.2.2

Created the project with:

natal init rn --interface om-next

Console log:

Looking for JS files in
   /Users/alanm/projects/coopsource/rn/native 

[5:28:20 PM] <START> Building Dependency Graph
[5:28:20 PM] <START> Crawling File System
[5:28:20 PM] <START> Loading bundles layout
[5:28:20 PM] <END>   Loading bundles layout (0ms)

React packager ready.

Error building DepdendencyGraph:
 TypeError: Cannot read property 'root' of null
    at /Users/alanm/projects/coopsource/rn/native/node_modules/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
    at tryCallOne (/Users/alanm/projects/coopsource/rn/native/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/alanm/projects/coopsource/rn/native/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/alanm/projects/coopsource/rn/native/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Process terminated. Press <enter> to close the window

**Comment by gphilipp** [comment]
I have the same issue.

Natal : 0.1.12
Xcode: 7.1.1
Node: v5.0.0

**Comment by gphilipp** [comment]
Upgrading watchman to 4.1 resolved the issue for me. I found the solution [here](https://github.com/facebook/react-native/issues/1875#issuecomment-118911271)

**Comment by kahunamoore** [comment]
Great - thanks. Will give it a try. Closing this issue.

**Comment by FengHuangDong** [comment]
I reload my watchman but still not 
![Uploading WX20170826-013745@2x.png…]()
