### ISSUE TITLE
Race with respect to compilation log?

### ISSUE THREAD

**Issue by mfikes** [dmotz/natal#36]
```
$ natal repl
Starting REPL
Warning: rlwrap is not installed.
Install it to make the REPL a much better experience with arrow key support.

[1] FutureApp on iPhone (usxxfikesmm3)

Connecting to FutureApp on iPhone (usxxfikesmm3) ...

fs.js:849
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/Volumes/Ambly-81C53995/watch.log'
  at Error (native)
  at Object.fs.statSync (fs.js:849:18)
  at new Tail (/usr/local/lib/node_modules/natal/node_modules/tail/tail.js:67:16)
  at Socket.onLeinOut (/usr/local/lib/node_modules/natal/natal.coffee:440:20)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:523:20)

$ natal repl
Starting REPL
Warning: rlwrap is not installed.
Install it to make the REPL a much better experience with arrow key support.

[1] FutureApp on iPhone (usxxfikesmm3)

Connecting to FutureApp on iPhone (usxxfikesmm3) ...

Watch compilation log available at: /Volumes/Ambly-81C53995/watch.log
Building ...
To quit, type: :cljs/quit
cljs.user=> ... done. Elapsed 0.322375363 seconds
cljs.user=> 
Watching paths: /Users/fikesm/Desktop/future-app/src
cljs.user=> 
```

**Comment by dmotz** [comment]
I saw this once as well. Just added a delay to fix it and I haven't seen it again.
