### ISSUE TITLE
natal repl fails sometimes

### ISSUE THREAD

**Issue by felipebueno** [dmotz/natal#37]
It happens from time to time and it usually works after a couple tries.

```
➜  hello-project  rlwrap natal repl
Starting REPL

[1] HelloProject on iPhone (felipes-mbp-vexwifi-com-br)

Connecting to HelloProject on iPhone (felipes-mbp-vexwifi-com-br) ...

fs.js:892
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/Volumes/Ambly-81C53995/watch.log'
  at Error (native)
  at Object.fs.statSync (fs.js:892:18)
  at new Tail (/usr/local/lib/node_modules/natal/node_modules/tail/tail.js:67:16)
  at Socket.onLeinOut (/usr/local/lib/node_modules/natal/natal.coffee:440:20)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:523:20)

➜  hello-project  rlwrap natal repl
Starting REPL

[1] HelloProject on iPhone (felipes-mbp-vexwifi-com-br)

Connecting to HelloProject on iPhone (felipes-mbp-vexwifi-com-br) ...

Watch compilation log available at: /Volumes/Ambly-81C53995/watch.log
Building ...
To quit, type: :cljs/quit
cljs.user=> ... done. Elapsed 0.442214224 seconds
cljs.user=> 
Watching paths: /Users/felipe/devel/playground/natal/hello-project/src
cljs.user=> 
```

**Comment by felipebueno** [comment]
Oh, sorry. It's duplicated #36

**Comment by dmotz** [comment]
Have you seen this happen with `0.1.12`?

**Comment by felipebueno** [comment]
No, I upgraded to `0.1.12` after I saw the other issue and it's working fine now. :)
