### ISSUE TITLE
natal init command failed

### ISSUE THREAD

**Issue by jiangts** [dmotz/natal#39]
I'm running into the following issue when trying to get started with Natal:

```
$ natal init nadal
Creating nadal

Creating Leiningen project
Updating Leiningen project
Creating React Native skeleton
Installing Pod dependencies
Updating Xcode project
Creating Natal config
Compiling ClojureScript
Compiling Xcode project
Command failed: xcodebuild -workspace native/ios/nadal.xcworkspace -scheme nadal -destination platform='iOS Simulator',OS=latest,id='DE89AB75-4E0B-4607-BD4F-3B145565C343' test
```

I'm running
Node 4.2.2 and XCode 7.1, Watchman 3.3.

When the command fails, I get

```
/.../nadal/native/node_modules/react-native/local-cli/cli.js:56
  const setupEnvScript = /^win/.test(process.platform)
  ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Process terminated. Press <enter> to close the window
```

**Comment by dmotz** [comment]
Are you using nvm? If so try upgrading nvm's version as well, as explained here: https://github.com/facebook/react-native/issues/3243#issuecomment-155677275

**Comment by Slowyn** [comment]
I have the same issue.
Also when I run natal repl it fails with error Error: spawn lein ENOENT.

XCode: 7.2,
Node: 5.5.0
react-native-cli: 0.1.10
