### ISSUE TITLE
Connecting REPL crashes app and gives error

### ISSUE THREAD

**Issue by scttnlsn** [dmotz/natal#45]
I initialized a new Natal application according to the README:

```
$ natal init FutureApp --interface om-next
```

This part works fine.  `natal launch` starts the app and everything works great.  Then I `cd future-app` and try connecting the REPL by running:

```
$ rlwrap natal repl
```

The app then crashes and I see the following in the REPL:

```
Starting REPL

[1] FutureApp on iPhone (scttnlsn-2)
java.io.IOException: Unable to mount WebDAV at http://127.0.0.1:49153
    at ambly.core$eval4850$fn__4851.invoke(core.clj:437)
    at clojure.lang.MultiFn.invoke(MultiFn.java:243)
    at ambly.core$setup.invoke(core.clj:521)
    at ambly.core.JscEnv._setup(core.clj:634)
    at cljs.repl$repl_STAR_$fn__4613.invoke(repl.cljc:827)
    at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1149)
    at cljs.repl$repl_STAR_.invoke(repl.cljc:824)
    at cljs.repl$repl.doInvoke(repl.cljc:977)
    at clojure.lang.RestFn.invoke(RestFn.java:559)
    at user$eval4939.invoke(form-init7598304267955659954.clj:4)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6745)
    at clojure.core$eval.invoke(core.clj:3081)
    at clojure.main$eval_opt.invoke(main.clj:289)
    at clojure.main$initialize.invoke(main.clj:308)
    at clojure.main$null_opt.invoke(main.clj:343)
    at clojure.main$main.doInvoke(main.clj:421)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
    at user$eval5.invoke(form-init7598304267955659954.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6772)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    at clojure.lang.Compiler.loadFile(Compiler.java:7165)
    at clojure.main$load_script.invoke(main.clj:275)
    at clojure.main$init_opt.invoke(main.clj:280)
    at clojure.main$initialize.invoke(main.clj:308)
    at clojure.main$null_opt.invoke(main.clj:343)
    at clojure.main$main.doInvoke(main.clj:421)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Not connected.
Watch compilation log available at: out/watch.log
To quit, type: :cljs/quit
cljs.user=> Compiling out/om/util.cljs
Compiling out/om/next.cljs
Compiling src/future_app/core.cljs
... done. Elapsed 2.812348488 seconds
cljs.user=> 
```

I'm using Natal version 0.1.13.

**Comment by scttnlsn** [comment]
I suspected this started happening when I upgraded from 0.1.12 to 0.1.13 but I encounter the same issue w/ 0.1.12

**Comment by scttnlsn** [comment]
When I load up the app in Xcode (via `natal xcode`) and then start the REPL, here's the error that's causing the app to crash:

![Xcode Error](https://dl.dropboxusercontent.com/u/10463543/natal-repl.png)

**Comment by dmotz** [comment]
Do you have the OSX firewall turned on?

**Comment by scttnlsn** [comment]
@dmotz Nope, turned off to my knowledge.  Preferences > Security & Privacy > Firewall says "Firewall: Off"

**Comment by scttnlsn** [comment]
Tried manually testing the WebDAV mount by following the steps described here: https://github.com/omcljs/ambly/wiki/Connectivity

I can run `mount_webdav http://127.0.0.1:49155 /Volumes/TestAmbly` without errors but nothing is actually mounted.

**Comment by dmotz** [comment]
Ah. I had the same persistent crashing at the same spot, which was only solved by turning off the OSX firewall.

Might want to reopen [this issue](https://github.com/omcljs/ambly/issues/104) and discuss there since I think this is out of Natal's scope.

**Comment by scttnlsn** [comment]
OK, thanks @dmotz

**Comment by dmotz** [comment]
Closing since this is being addressed on Ambly's end.
