### ISSUE TITLE
Use with Emacs/Cider

### ISSUE THREAD

**Issue by maacl** [dmotz/natal#5]
Changing to the project dir and executing `cider-jack-in` and:

```
(let [repl-env (ambly.core/repl-env)]
  (cljs.repl/repl repl-env
    :watch "src"
    :watch-fn
      (fn []
        (cljs.repl/load-file repl-env
          "src/meet_npv/core.cljs"))
    :analyze-path "src"))
```

gives me a repl but with a stdin prompt in the mini buffer, and no input is possible from the repl but only from the mini buffer. It appears easy to fix but even after looking at the code I cannot figure out where to intervene.

**Comment by mfikes** [comment]
I wonder if this is an underlying issue with Ambly and its use of `read-line`. It might be worth trying an experiment passing `:choose-first-discovered true` as described at https://github.com/omcljs/ambly/wiki/REPL-in-Cursive

**Comment by maacl** [comment]
This works, thanks a lot.

**Comment by dmotz** [comment]
Latest version of Natal uses `:choose-first-discovered` by default so that should fix this issue.

**Comment by felipebueno** [comment]
Hello.

Sorry for commenting on a closed issue but I'm having the same problem :(

@maacl Can you teach me how you did that, please? :)

I tried using the `:choose-first-discovered true` option but it didn't work.

**Comment by maacl** [comment]
@felipebueno I am afraid all I did was:

```
(require
  '[cljs.repl :as repl]
  '[cemerick.piggieback]
  '[ambly.core :as ambly])

(cemerick.piggieback/cljs-repl
  (ambly/repl-env :choose-first-discovered true))
```

**Comment by dmotz** [comment]
@felipebueno Run `npm up -g natal` to get the latest Natal. `natal repl` should use `choose-first-discovered` by default.

**Comment by felipebueno** [comment]
Oh, thanks, @maacl ! It worked :)

Nice, @dmotz . I'm going to try it now. Thanks :)

**Comment by felipebueno** [comment]
@dmotz I upgraded `natal` to the latest version but now I can't connect to the repl even from the command line. And the app crashes when it's trying to connect.

Here's the log:

```
➜  future-app  natal repl
Starting REPL

[1] FutureApp on iPhone (felipes-mbp-vexwifi-com-br)
java.io.IOException: Unable to mount WebDAV at http://127.0.0.1:49153
    at ambly.core$eval4775$fn__4776.invoke(core.clj:437)
    at clojure.lang.MultiFn.invoke(MultiFn.java:243)
    at ambly.core$setup.invoke(core.clj:521)
    at ambly.core.JscEnv._setup(core.clj:634)
    at cljs.repl$repl_STAR_$fn__4538.invoke(repl.cljc:826)
    at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1146)
    at cljs.repl$repl_STAR_.invoke(repl.cljc:823)
    at cljs.repl$repl.doInvoke(repl.cljc:976)
    at clojure.lang.RestFn.invoke(RestFn.java:559)
    at user$eval4864.invoke(form-init1596536718680274117.clj:4)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6745)
    at clojure.core$eval.invoke(core.clj:3081)
    at clojure.main$eval_opt.invoke(main.clj:289)
    at clojure.main$initialize.invoke(main.clj:308)
    at clojure.main$null_opt.invoke(main.clj:343)
    at clojure.main$main.doInvoke(main.clj:421)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
    at user$eval5.invoke(form-init1596536718680274117.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6772)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    at clojure.lang.Compiler.loadFile(Compiler.java:7165)
    at clojure.main$load_script.invoke(main.clj:275)
    at clojure.main$init_opt.invoke(main.clj:280)
    at clojure.main$initialize.invoke(main.clj:308)
    at clojure.main$null_opt.invoke(main.clj:343)
    at clojure.main$main.doInvoke(main.clj:421)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Not connected.
Watch compilation log available at: out/watch.log
To quit, type: :cljs/quit
cljs.user=> 
```

**Comment by felipebueno** [comment]
hmm never mind. I created a new project (`natal init ...`) and it's working. Not sure what went wrong the first time.

**Comment by felipebueno** [comment]
Hey @dmotz sorry to bother you again :smile: but I think it's still necessary to use `piggieback` to get `natal repl` working properly with `cider`, isn't it?  That's how I'm doing now. Am I missing something?

**Comment by felipebueno** [comment]
Oh, btw I'm not complaining. Natal is awesome! :+1: :smiley: 

Please keep up the good work.

**Comment by dmotz** [comment]
@felipebueno Yep I think you're right. I'll try to address this in an update soon. And thanks!
